# Generated by Django 2.1.15 on 2025-03-13 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarbonTracker', '0002_emissionrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emissionrecord',
            name='user',
        ),
        migrations.DeleteModel(
            name='EmissionRecord',
        ),
    ]
